/*
 * Board : ESP32 Mini (ESP32-C3)
 * Display: 1.3" 128×64 SH1106 @ 0x3C
 * Library: Adafruit SH110X
 * Animations generated by OLED Display Animation Maker — https://www.oledanimationmaker.com/
 */

// OLED Display
// GPIO8 - SDA
// GPIO9 - SCL/SCK
// 3.3V - OLED VCC
// GND - OLED GND

// Cuddle button
// GPIO0 / GND

// Motion sensor
// GPIO1 / 5V / GND 

/*
 * Display a random startup animation
 * Initialize sleepy timer
 * Initialize needcare timer
 * Initialize every-second-timer with dedicated ISR routine
 * Initialize motion sensor with dedicated ISR routine
 * Initialize cuddle button with dedicated ISR routine
 * state = HAPPY
 * loop()
 *   IF state == HAPPY
 *     Choose randomly a happy animation
 *     WHILE state == HAPPY && N fois
 *       Display happy animation
 *   IF state == SLEEPY
 *     Choose randomly a sleepy animation
 *     WHILE state == SLEEPY
 *       Display sleepy animation
 *   IF state == NEEDCARE
 *     Choose randomly a needcare animation
 *     WHILE state == NEEDY
 *       Display needcare animation
 *   IF state == LOVY
 *     Choose randomly a love animation
 *       Display love animation
 *     state = HAPPY
 *
 * every_second_timer() & ISR()
 *   Increment sleepy timer
 *   Increment needcare timer
 *   IF sleepy timer reached && state == HAPPY
 *     state = SLEEPY
 *   IF needcare timer reached
 *     state = NEEDY
 *
 * motionISR()
 *   IF state == SLEEPY
 *     Reset sleepy timer
 *     state = HAPPY
 *
 * buttonISR()
 *   Reset sleepy timer
 *   Reset needcare timer
 *   state = LOVY
 *
 */

#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>

#include "tamafrogi_happy1.h"
#include "tamafrogi_happy2.h"
#include "tamafrogi_love1.h"
#include "tamafrogi_need1.h"
#include "tamafrogi_sleep1.h"

// Display settings
#define SCREEN_WIDTH  128
#define SCREEN_HEIGHT 64
#define OLED_RESET    -1
#define SCREEN_ADDR   0x3C

// Motion sensor settings
// D3 pin
#define motionSensor 1

// Cuddle button settings
// D2 pin
#define cuddleButton 0

// Finite-state automaton settings
enum frogi_states { HAPPY, SLEEPY, NEEDY, LOVY };
frogi_states frogi_state = HAPPY;
#define DELAY_SLEEPY_SEC 10
#define DELAY_NEEDY_SEC 30
#define HAPPY_ANIM_DISPLAY_TIMES 5

// other constants
#define HAPPY_ANIM_NUMBER 2 // number of happy animations (tamafrogi_happy1, etc)

// global variables
hw_timer_t * timer = NULL;
unsigned int seconds_count_sleepy = 0;
unsigned int seconds_count_needy = 0;
uint8_t current_happy_anim = 0;

Adafruit_SH1106G display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

void setup() {
  Serial.println(F("TAMAFROGI AWAKING"));
  
  // Serial init
  Serial.begin(9600);

  // Display init
  if (!display.begin(SCREEN_ADDR, true)) {
    Serial.println(F("SH1106 allocation failed"));
    for (;;);
  }
  display.setRotation(0);
  display.clearDisplay();
  display.display();
  Serial.println(F("Display initialized"));

  // Motion sensor init
  pinMode(motionSensor, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(motionSensor), motionISR, RISING);
  Serial.println(F("Motion sensor initialized"));
  
  // Cuddle button init
  pinMode(cuddleButton, INPUT_PULLUP);
  digitalWrite(cuddleButton, HIGH); // avoid getting a fake button pressed just after attaching interrupt
  attachInterrupt(digitalPinToInterrupt(cuddleButton), buttonISR, FALLING);
  Serial.println(F("Cuddle button initialized"));
  

  // Timer init
  init_every_second_timer();
}

void loop() {
  uint8_t anim_count = 0;
  
  disp_startup();
  
  Serial.print(F("loop - ")); print_state();
  switch(frogi_state) {
    case HAPPY: {
      // display a happy animation a few times (then next loop will display another animation if still happy)
      for(anim_count = 0; frogi_state == HAPPY && anim_count < HAPPY_ANIM_DISPLAY_TIMES; anim_count++) {
        disp_happy();
      }
      break;
    }
    case SLEEPY: {
      // display same animation while not awaken
      while(frogi_state == SLEEPY) {
        disp_sleepy();
      }
      break;
    }
    case NEEDY: {
      // display same animation while not taken care of
      while(frogi_state == NEEDY) {
        disp_needcare();
      }
      break;
    }
    case LOVY: {
      // display a love animation one time then become happy
      disp_love();
      change_state(HAPPY);
      break;
    }
  }

  // avoid full cpu loops in unexpected cases
  delay(0.5);

}

// ---------------- //
// Display functions
// ---------------- //

//void disp_anim(const uint8_t* anim_frames[], const uint8_t num_frames) {
void disp_anim(uint8_t* anim_frames[], uint8_t num_frames) {
  static uint8_t frameIdx = 0;
  for(frameIdx = 0; frameIdx < num_frames; frameIdx++) {
    display.clearDisplay();
    display.drawBitmap(0, 0, anim_frames[frameIdx], 128, 64, SH110X_WHITE);
    display.display();
    frameIdx = (frameIdx + 1) % num_frames;
    //delay(67);
    delay(133);
  }  
}

void disp_startup() {
}

/*const uint8_t** anim_happy_all_frames[] = {anim_happy1_frames, anim_happy2_frames};
const uint8_t anim_happy_all_numFrames[] = {9, 38};*/

uint8_t** frames;
uint8_t numFrames;

void disp_happy() {

  /*frames = (uint8_t*)anim_happy_all_frames[current_happy_anim];
  numFrames = anim_happy_all_numFrames[current_happy_anim];*/
  /*switch(current_happy_anim) {
    case 0:
      frames = (uint8_t**)anim_happy1_frames;
      numFrames = anim_happy1_numFrames;
      break;
    case 1:
      frames = (uint8_t**)anim_happy2_frames;
      numFrames = anim_happy2_numFrames;
      break;
      
  }*/
  frames = (uint8_t**)anim_happy1_frames;
  numFrames = anim_happy1_numFrames;
  disp_anim(frames, numFrames);
  //Serial.println(F("DISPLAY HAPPY ANIMATION")); delay(5000); // DEBUG
}

void disp_sleepy() {
  
  frames = (uint8_t**)anim_sleep1_frames;
  numFrames = anim_sleep1_numFrames;
  
  //disp_anim(anim_sleep1_frames, anim_sleep1_numFrames);
  disp_anim(frames, numFrames);
  //Serial.println(F("DISPLAY SLEEPY ANIMATION")); delay(5000); // DEBUG
}

void disp_needcare() {
  frames = (uint8_t**)anim_need1_frames;
  numFrames = anim_need1_numFrames;
  
  //disp_anim(anim_need1_frames, anim_need1_numFrames);
  disp_anim(frames, numFrames);
  //Serial.println(F("DISPLAY NEEDY ANIMATION")); delay(5000); // DEBUG
}

void disp_love() {
  frames = (uint8_t**)anim_love1_frames;
  numFrames = anim_love1_numFrames;
  
  //disp_anim(anim_love1_frames, anim_love1_numFrames);
  disp_anim(frames, numFrames);
  //Serial.println("DISPLAY LOVY ANIMATION"); delay(5000); // DEBUG
}


// ---------------- //
// Finite-state automaton functions
// ---------------- //

void init_every_second_timer() {

  // Set timer frequency to 1Mhz
  timer = timerBegin(1000000);

  // Attach onTimer function to our timer.
  timerAttachInterrupt(timer, &onTimer);

  // Set alarm to call onTimer function every second (value in microseconds).
  // Repeat the alarm (third parameter) with unlimited count = 0 (fourth parameter).
  timerAlarm(timer, 1000000, true, 0);
  
}

// TIMER VECTOR, gets called once a second (depends on prescaler and match register)
void ARDUINO_ISR_ATTR onTimer()
{
  //Serial.println(F("every-second-ISR called"));
  seconds_count_sleepy++;
  seconds_count_needy++;
  if (seconds_count_sleepy >= DELAY_SLEEPY_SEC
      && frogi_state == HAPPY) {
    change_state(SLEEPY);
  }
  if (seconds_count_needy >= DELAY_NEEDY_SEC
      && frogi_state != NEEDY) {
    change_state(NEEDY);
  }
}

void change_state(frogi_states new_state) {
  frogi_state = new_state;
  print_state();
}

void print_state() {
  Serial.print(F("State "));
  switch(frogi_state) {
    case HAPPY: { Serial.println(F("HAPPY")); break; }
    case SLEEPY: { Serial.println(F("SLEEPY")); break; }
    case NEEDY: { Serial.println(F("NEEDY")); break; }
    case LOVY: { Serial.println(F("LOVY")); break; }
  }
  
}

// ---------------- //
// Motion sensor functions
// ---------------- //

void motionISR() {
  Serial.println(F("Motion detected"));
  seconds_count_sleepy = 0;
  if (frogi_state == SLEEPY) {
    change_state(HAPPY);
  }
}

// ---------------- //
// Cuddle button functions
// ---------------- //

void buttonISR() {
  Serial.println(F("Cuddle detected"));
  seconds_count_sleepy = 0;
  seconds_count_needy = 0;
  change_state(LOVY);
}


// ---------------- //
// Behavior functions
// ---------------- //
void choose_new_happy_anim() {
  Serial.println(F("Choose new happy anim"));
  current_happy_anim = (current_happy_anim + 1) % HAPPY_ANIM_NUMBER;
}
